### ISSUE TITLE
For the eda_script, in order to generate images successfully, the 531 environment has to be used. 

### ISSUE THREAD

**Issue by YHuUBC** [UBC-MDS/energy_efficiency_analysis#35]
The base environment and the 573 environments cannot work. Both environments generate errors.
For base, even though with all the required libraries and packages, it says 'ValueError: No enabled saver found that supports format='png''
For 573, it says 'json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)'

**Comment by YHuUBC** [comment]
It could work on the 573 environment on other computers

**Comment by Suraporn** [comment]
Checked, need to update new env file.
