### ISSUE TITLE
running model_predict file 

### ISSUE THREAD

**Issue by MNBhat** [UBC-MDS/energy_efficiency_analysis#39]
For running model_predict file environment of 573 was used. Additionally installing docopt and request in the env
Commands are 
conda install -c anaconda docopt
conda install -c anaconda requests

**Comment by YHuUBC** [comment]
The First attempt to run it was not successful, could you please update the usage section of the model_predict.py? Thank you.

**Comment by Suraporn** [comment]
Completed
