### ISSUE TITLE
model_predict.py could not run facing X_train undefined error

### ISSUE THREAD

**Issue by Suraporn** [UBC-MDS/energy_efficiency_analysis#46]
$ python src/model_predict.py --train_file='data/processed/train_df.csv'  --test_file='data/processed/test_df.csv' --out_file=src/training_score.png 
Traceback (most recent call last):
  File "/Users/boy_mbp14p/mds_block3/energy_efficiency_analysis/src/model_predict.py", line 72, in <module>
    main( opt["--train_file"],opt["--test_file"] , opt["--out_file"])
  File "/Users/boy_mbp14p/mds_block3/energy_efficiency_analysis/src/model_predict.py", line 51, in main
    scores[modelname] = pd.DataFrame(cross_validate(pipe, X_train,y_train, return_train_score= True, scoring = 'r2')).agg(['mean', 'std']).round(3).T
NameError: name 'X_train' is not defined

Need to add,

X_train, y_train = train_df.drop(columns=["Heating Load"]), train_df["Heating Load"]
X_test, y_test = test_df.drop(columns=["Heating Load"]), test_df["Heating Load"]

**Comment by MNBhat** [comment]
fixed
